### ISSUE TITLE
KafkaHandler annotation support

### ISSUE THREAD

**Issue by andreoss** [springwolf/springwolf-kafka#1]
KafkaListener is only supported for methods https://github.com/springwolf/springwolf-kafka/blob/master/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/KafkaChannelsScanner.java#L42

But KafkaListener can be used to annotated a class, with method annotated by KafkaHandler inside this class. [1]

1: https://docs.spring.io/spring-kafka/api/org/springframework/kafka/annotation/KafkaHandler.html

**Comment by stavshamir** [comment]
Thanks for the PR! Would you mind providing an example of your usage of this annotation?

**Comment by andreoss** [comment]
@stavshamir 
A simple example would be (bellow), this listener would dispatch by the type of the received object. 
Note that `KafkaListener` is a type-level annotation on enclosing class, so `KafkaHandler` annotated methods could be inherited from parent class. 

```
@Service
@KafkaListener(topics = {"${topic}"})
public class KafkaEndpoints extends AbstractEndpoints {

    @KafkaHandler
    @SendTo("!{source.headers['REPLY_TO']}")
    public Message<ResponseOne> receive(
        final RequestOne dto,
        final @Headers Map<String, Object> headers,
        final Acknowledgment ack
    ) {
        ...
    }

    @KafkaHandler
    @SendTo("!{source.headers['REPLY_TO']}")
    public Message<ResponseTwo> receive(
        final RequestTwo dto,
        final @Headers Map<String, Object> headers,
        final Acknowledgment ack
    ) {
        ...
    }
}

```

**Comment by stavshamir** [comment]
Thanks for the detailed response. Since it's quite different than how the current flow, it will probably take a while to implement. 

If you'd like to try and start working on this I would be glad to accept contributions and discuss with you about the implementation.

If you're interested you can contact me by e-mail or linkedin.

**Comment by stavshamir** [comment]
Closed due to inactivity.
