### ISSUE TITLE
The groupId string value of KafkaListener is not resolved

### ISSUE THREAD

**Issue by chris0550** [springwolf/springwolf-kafka#2]
Hello,

I faced following bug:

**KafkaListener:**
```
@KafkaListener(topics = "${myproperties.kafka.topic}", groupId = "${myproperties.kafka.consumer.group.id}")
```
**Properties:**
```
myproperties.kafka.topic=myTopic
myproperties.kafka.consumer.group.id=myConsumerGroup
```
leads to following result:
![grafik](https://user-images.githubusercontent.com/13584933/109158155-49eac880-7773-11eb-8db0-b31a1634af49.png)
The topic string value is resolved corret, but the groupId is not.

Edit: Created a PR for the fix

**Comment by stavshamir** [comment]
Hi @chris0550, thanks for the details report and fix.
